<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/4/27 0027
 * Time: 上午 10:25
 */

namespace Home\Controller;


class LoginController extends HomeController{

    public function login()
    {
        parent::login(); // TODO: Change the autogenerated stub

    }
}